kind: Deployment
apiVersion: apps/v1
metadata:
  name: grafana-deployment
  namespace: "monitoring_namespace"
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
    spec:
      volumes:
        - name: datasource-config
          configMap:
            name: grafana-datasources
            defaultMode: 420
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: grafana
          env:
            - name: GF_SERVER_ROOT_URL
              value: 'your route address'
            - name: GF_SERVER_ENABLE_GZIP
              value: 'true'
            - name: GF_DATASOURCES_PROXY_TIMEOUT
              value: '120'
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: 'true'
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-credentials
                  key: GF_SECURITY_ADMIN_PASSWORD
            - name: GF_USERS_ALLOW_SIGN_UP
              value: 'false'
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: datasource-config
              readOnly: true
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-storage
              mountPath: /var/lib/grafana
          terminationMessagePolicy: File
          image: 'quay.io/serkanozmen/grafana:latest'